---
title: "HW2_Task1"
author: "Corinna Hong"
date: "February 12, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Thoughts on Open Science

Some important goals of open science are increased public access to academic papers, better transparency and accountability in research, and data and code sharing (McKiernan et al., 2016; Bahlai et al., 2019). Open science practices can also involve the general public in a greater capacity. As Bahlai et al. (2019) point out, research in all fields is performed with, not separate from society; non-scientists participate in, fund, and benefit from scientific research. Transparency in the process can strengthen the relationship between researchers and the general public. Open science practices can benefit researchers through increased citations and media coverage, new collaborations, and retained rights to manuscripts and materials when publishing in open access journals (McKiernan et al., 2016). However, there are also drawbacks to complete open-access. 
</br>

Bahlai et al. (2019) write that althoug
h in theory open science sounds good, it is not necessarily accessible to all. The way that open science is currently approached excludes people with sensory disabilities, limited internet accessibility, and economic limitations. It can also pose problems for researchers, especially early career scientists, women, and people of color (POC). Open-access journals are often seen as less prestigious. This could prove detrimental for early scientists who might not be able to advance their career due to publishing in these “less impactful” journals. Additionally, full transparency in the feedback process can exacerbate existing unconscious biases against women and POC (Bahlai et al., 2019). The traditional, double-masked review process helps eliminate, or at least reduce, unconscious bias in reviews. Finally, making intermediate products such as datasets and code available to the public poses a risk to scientists with fewer resources available to dedicate to full-time research. For these researches, the risk of having their work published without them is higher than in the traditional process (Bahlai et al. 2019). A redesign of current approaches to open science is necessary to address these limitations and create an inclusive, equitable, and accessible system.
</br>

In my own work, the use of R and GitHub have been a necessary tool for ensuring reproducibility. After being introduced to both, I now conduct all research projects and data work in R and made it available on GitHub as a public repository. Additionally, my master’s group project also utilized approaches and tools to ensure reproducibility. All data was collected in a third-party app that created the raw dataset used in our analysis. The raw data was then wrangled, visualized, and analyzed in R. However, there are still limitations to accessibility in my workflow. One big accessibility issue that is quite easy to address is the use of colors that are not discernable to those with color vision deficiencies. I could overcome this by creating a second version of my final project using color palettes that remedy this accessibility issue.  Another limitation in my work is that it is currently only shared within the UCSB community. My data science work has either been assignments submitted directly to professors, or research presented to students and faculty. Moving forward, beyond UCSB, if will be important to share my work in formats that are tailored to a public audience. 

</br>
**References**
</br>
Bahlai, C., Bartlett, L. J., Burgio, K. R., Fournier, A. M. V., Keiser, C. N., Poisot, T., & Whitney, K. S. (2019, April). Open Science Isn’t Always Open to All Scientists. *American Scientist, 107*(2), 78.https://www.americanscientist.org/article/open-science-isnt-always-open-to-all-scientists
</br>

McKiernan, E. C., Bourne, P. E., Brown, C. T., Buck, S., Kenall, A., Lin, J., McDougall, D., Nosek, B. A., & Ram, K. (2016). Point of View: How open science helps researchers succeed. *ELife*. https://doi.org/10.7554/eLife.16800.001
